Ejercicio: 
        gcc -Os -S -o Ejercicio.s Ejercicio.c //forzamos la detención del proceso para sacar el s
        nano Ejercicio.s //enviamos directo a la edición del s para limpiarlo un poco
Compilar: 
        /*usamos g++ para que soporte el printf*/
        g++ Ejercicio.s -g -o Ejercicio //codigo para generar el ejcutable

Run: 
        ./Ejercicio //ejecutamos
Limpiar:
        rm Ejercicio //el ejecutable solamente lo borramos
